# This will either create a new jenkins load balancer or return the old one
- name: Delete jenkins load balancer
  local_action:
    module: rax_clb
    credentials: "{{ creds_path }}"
    name: "jenkins_lb"
    port: "80"
    protocol: "HTTP"
    type: PUBLIC
    timeout: 30
    region: "DFW"
    wait: yes
    wait_timeout: 600
    state: absent
  register: jenkins_load_balancer

# This will either create a new sonar load balancer or return the old one
- name: Delete sonar load balancer
  local_action:
    module: rax_clb
    credentials: "{{ creds_path }}"
    name: "sonar_lb"
    port: "80"
    protocol: "HTTP"
    type: PUBLIC
    timeout: 30
    region: "DFW"
    wait: yes
    wait_timeout: 600
    state: absent
  register: sonar_load_balancer
    
# Create jenkins node
- name: Delete jenkins server
  local_action:    
    module: rax
    credentials: "{{ creds_path }}"
    name: "jenkins"
    flavor: "performance1-4"
    image: "a1558fdc-3182-4a0f-b48a-aa900a5826c3"
    region: "DFW"
    state: absent
    count: "1"
    group: "jenkins"
    count_offset: 1
    exact_count: yes
    wait: yes
    wait_timeout: 180
  ignore_errors: yes
  register: delete_result
  register: jenkins_nodes
    
# Create jenkins node
- name: Delete jenkins server...again
  local_action:    
    module: rax
    credentials: "{{ creds_path }}"
    name: "jenkins"
    flavor: "performance1-4"
    image: "a1558fdc-3182-4a0f-b48a-aa900a5826c3"
    region: "DFW"
    state: absent
    count: "1"
    group: "jenkins"
    count_offset: 1
    exact_count: yes
    wait: yes
    wait_timeout: 600
  ignore_errors: yes
  when: delete_result|failed
  register: jenkins_nodes
