# This will either create a new jenkins load balancer or return the old one
- name: Create jenkins load balancer
  local_action:
    module: rax_clb
    credentials: "{{ creds_path }}"
    name: "jenkins_lb"
    port: "80"
    protocol: "HTTP"
    type: PUBLIC
    timeout: 30
    region: "DFW"
    wait: yes
    wait_timeout: 600
    state: present
  register: jenkins_load_balancer

# This will either create a new sonar load balancer or return the old one
- name: Create sonar load balancer
  local_action:
    module: rax_clb
    credentials: "{{ creds_path }}"
    name: "sonar_lb"
    port: "80"
    protocol: "HTTP"
    type: PUBLIC
    timeout: 30
    region: "DFW"
    wait: yes
    wait_timeout: 600
    state: present
  register: sonar_load_balancer
   
# Create jenkins node
- name: Create jenkins server
  local_action:    
    module: rax
    credentials: "{{ creds_path }}"
    name: "jenkins"
    flavor: "performance1-4"
    image: "a1558fdc-3182-4a0f-b48a-aa900a5826c3"
    region: "DFW"
    networks:
      - public
      - private
    state: present
    count: "1"
    group: "jenkins"
    count_offset: 1
    exact_count: yes
    wait: yes
    wait_timeout: 600
  register: jenkins_nodes

# Add jenkins servers to jenkins group
- name: Add server to jenkins host group
  local_action:
    module: add_host
    hostname: "{{ item.name }}"
    ansible_ssh_host: "{{ item.rax_accessipv4 }}"
    ansible_ssh_pass: "{{ item.rax_adminpass }}"
    ansible_ssh_user: root
    groupname: jenkins
  with_items: jenkins_nodes.success
  when: jenkins_nodes.action == "create"

# Add jenkins servers to jenkins load balancer
- name: Add Jenkins servers to Jenkins Load balancer
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_path }}"
    load_balancer_id: "{{ jenkins_load_balancer.balancer.id }}"
    address: "{{ item.rax_addresses.private[0].addr }}"
    port: "8080" 
    condition: enabled
    type: primary
    wait: yes
    wait_timeout: 600
    region: "DFW"
  with_items: jenkins_nodes.success
  when: jenkins_nodes.action == "create"

# Add jenkins servers to sonar load balancer
- name: Add Jenkins servers to Sonar Load balancer
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_path }}"
    load_balancer_id: "{{ sonar_load_balancer.balancer.id }}"
    address: "{{ item.rax_addresses.private[0].addr }}"
    port: "9000" 
    condition: enabled
    type: primary
    wait: yes
    wait_timeout: 600
    region: "DFW"
  with_items: jenkins_nodes.success
  when: jenkins_nodes.action == "create"